// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportsUIClient is the client API for ReportsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportsUIClient interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (ReportsUI_ListDocumentSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type reportsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewReportsUIClient(cc grpc.ClientConnInterface) ReportsUIClient {
	return &reportsUIClient{cc}
}

func (c *reportsUIClient) ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (ReportsUI_ListDocumentSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReportsUI_ServiceDesc.Streams[0], "/v1.ReportsUI/ListDocumentSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &reportsUIListDocumentSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReportsUI_ListDocumentSpecsClient interface {
	Recv() (*ListDocumentSpecsResponse, error)
	grpc.ClientStream
}

type reportsUIListDocumentSpecsClient struct {
	grpc.ClientStream
}

func (x *reportsUIListDocumentSpecsClient) Recv() (*ListDocumentSpecsResponse, error) {
	m := new(ListDocumentSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reportsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ReportsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportsUIServer is the server API for ReportsUI service.
// All implementations must embed UnimplementedReportsUIServer
// for forward compatibility
type ReportsUIServer interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(*ListDocumentSpecsRequest, ReportsUI_ListDocumentSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedReportsUIServer()
}

// UnimplementedReportsUIServer must be embedded to have forward compatible implementations.
type UnimplementedReportsUIServer struct {
}

func (UnimplementedReportsUIServer) ListDocumentSpecs(*ListDocumentSpecsRequest, ReportsUI_ListDocumentSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDocumentSpecs not implemented")
}
func (UnimplementedReportsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedReportsUIServer) mustEmbedUnimplementedReportsUIServer() {}

// UnsafeReportsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportsUIServer will
// result in compilation errors.
type UnsafeReportsUIServer interface {
	mustEmbedUnimplementedReportsUIServer()
}

func RegisterReportsUIServer(s grpc.ServiceRegistrar, srv ReportsUIServer) {
	s.RegisterService(&ReportsUI_ServiceDesc, srv)
}

func _ReportsUI_ListDocumentSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReportsUIServer).ListDocumentSpecs(m, &reportsUIListDocumentSpecsServer{stream})
}

type ReportsUI_ListDocumentSpecsServer interface {
	Send(*ListDocumentSpecsResponse) error
	grpc.ServerStream
}

type reportsUIListDocumentSpecsServer struct {
	grpc.ServerStream
}

func (x *reportsUIListDocumentSpecsServer) Send(m *ListDocumentSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReportsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ReportsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportsUI_ServiceDesc is the grpc.ServiceDesc for ReportsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ReportsUI",
	HandlerType: (*ReportsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ReportsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDocumentSpecs",
			Handler:       _ReportsUI_ListDocumentSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reports-ui.proto",
}
